# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Setup keyfile
  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = null;
  };

  # Enable swap on luks
  boot.initrd.luks.devices."luks-f05d9469-f3cb-4d27-aaf7-355e1abb5a54".device = "/dev/disk/by-uuid/f05d9469-f3cb-4d27-aaf7-355e1abb5a54";
  boot.initrd.luks.devices."luks-f05d9469-f3cb-4d27-aaf7-355e1abb5a54".keyFile = "/crypto_keyfile.bin";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/abd6d5fe-2936-4fb0-882a-b117eff6ebb7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d6961502-f4a8-4318-8c01-5831df05ad2e".device = "/dev/disk/by-uuid/d6961502-f4a8-4318-8c01-5831df05ad2e";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/0E5F-1BDF";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/df14d0a2-4b83-449f-9a45-5f89f1c29ccf"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
